version: '3.8'
services:
  base:
    build: ./docker
    ports: ["8080:8080"]
    volumes:
      - ./config:/app/config:ro
  sentiment:
    build: ./jobs/imdb-sentiment
    ports: ["8081:8081"]
    volumes: 
      - ./config:/app/config:ro
  healthcheck:
    build: ./healthcheck
    depends_on: [base, sentiment]
    volumes:
      - ./config:/app/config:ro
